// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/jul003",
            "email": "indra@ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/deletegadget/{id}": {
            "delete": {
                "description": "Hapus data gadget.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gadget"
                ],
                "summary": "Delete data Gadget.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/gadget": {
            "get": {
                "description": "Mengambil semua data gadget.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gadget"
                ],
                "summary": "Get All Data Gadget.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Gadget"
                        }
                    }
                }
            }
        },
        "/gadget/{id}": {
            "get": {
                "description": "Ambil per ID data gadget.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gadget"
                ],
                "summary": "Get By ID Data Gadgets.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Gadget"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/insertgadget": {
            "post": {
                "description": "Input data gadget.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gadget"
                ],
                "summary": "Insert data Gadget.",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqGadget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Gadget"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/insertreview": {
            "post": {
                "description": "Input data review.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review"
                ],
                "summary": "Insert data Review.",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqReview"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Review"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/review": {
            "get": {
                "description": "Mengambil semua data review.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review"
                ],
                "summary": "Get All Data Review.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Gadget"
                        }
                    }
                }
            }
        },
        "/updategadget/{id}": {
            "put": {
                "description": "Ubah data gadget.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Gadget"
                ],
                "summary": "Update data Gadegt.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqGadget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Gadget"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Gadget": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "123456789"
                },
                "deskripsi": {
                    "type": "string",
                    "example": "Smartphone dengan layar Super Retina XDR 6.1 inci dan kamera ganda 12 MP."
                },
                "harga": {
                    "type": "number",
                    "example": 15000000
                },
                "merk": {
                    "type": "string",
                    "example": "Apple"
                },
                "nama": {
                    "type": "string",
                    "example": "iPhone 13"
                },
                "spesifikasi": {
                    "$ref": "#/definitions/controller.Spesifikasi"
                }
            }
        },
        "controller.ReqGadget": {
            "type": "object",
            "properties": {
                "deskripsi": {
                    "type": "string",
                    "example": "Smartphone dengan layar Super Retina XDR 6.1 inci dan kamera ganda 12 MP."
                },
                "harga": {
                    "type": "number",
                    "example": 15000000
                },
                "merk": {
                    "type": "string",
                    "example": "Apple"
                },
                "nama": {
                    "type": "string",
                    "example": "iPhone 13"
                },
                "spesifikasi": {
                    "$ref": "#/definitions/controller.ReqSpesifikasi"
                }
            }
        },
        "controller.ReqReview": {
            "type": "object",
            "properties": {
                "gadget_id": {
                    "type": "string",
                    "example": "3344556677"
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "review": {
                    "type": "string",
                    "example": "Luar biasa! Kinerja cepat dan kamera sangat bagus."
                },
                "user_id": {
                    "type": "string",
                    "example": "2233445566"
                }
            }
        },
        "controller.ReqSpesifikasi": {
            "type": "object",
            "properties": {
                "prosesor": {
                    "type": "string",
                    "example": "A15 Bionic"
                },
                "ram": {
                    "type": "integer",
                    "example": 6
                },
                "storage": {
                    "type": "integer",
                    "example": 128
                }
            }
        },
        "controller.Review": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "1122334455"
                },
                "datetime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-07-20T00:00:00Z"
                },
                "gadget_id": {
                    "type": "string",
                    "example": "3344556677"
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                },
                "review": {
                    "type": "string",
                    "example": "Luar biasa! Kinerja cepat dan kamera sangat bagus."
                },
                "user_id": {
                    "type": "string",
                    "example": "2233445566"
                }
            }
        },
        "controller.Spesifikasi": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "987654321"
                },
                "prosesor": {
                    "type": "string",
                    "example": "A15 Bionic"
                },
                "ram": {
                    "type": "integer",
                    "example": 6
                },
                "storage": {
                    "type": "integer",
                    "example": 128
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "tb-2024-2df3fc45e2ad.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "TES SWAGGER ULBI",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
