basePath: /
definitions:
  controller.Gadget:
    properties:
      _id:
        example: "123456789"
        type: string
      deskripsi:
        example: Smartphone dengan layar Super Retina XDR 6.1 inci dan kamera ganda
          12 MP.
        type: string
      harga:
        example: 15000000
        type: number
      merk:
        example: Apple
        type: string
      nama:
        example: iPhone 13
        type: string
      spesifikasi:
        $ref: '#/definitions/controller.Spesifikasi'
    type: object
  controller.ReqGadget:
    properties:
      deskripsi:
        example: Smartphone dengan layar Super Retina XDR 6.1 inci dan kamera ganda
          12 MP.
        type: string
      harga:
        example: 15000000
        type: number
      merk:
        example: Apple
        type: string
      nama:
        example: iPhone 13
        type: string
      spesifikasi:
        $ref: '#/definitions/controller.ReqSpesifikasi'
    type: object
  controller.ReqReview:
    properties:
      gadget_id:
        example: "3344556677"
        type: string
      rating:
        example: 5
        type: integer
      review:
        example: Luar biasa! Kinerja cepat dan kamera sangat bagus.
        type: string
      user_id:
        example: "2233445566"
        type: string
    type: object
  controller.ReqSpesifikasi:
    properties:
      prosesor:
        example: A15 Bionic
        type: string
      ram:
        example: 6
        type: integer
      storage:
        example: 128
        type: integer
    type: object
  controller.Review:
    properties:
      _id:
        example: "1122334455"
        type: string
      datetime:
        example: "2024-07-20T00:00:00Z"
        format: date-time
        type: string
      gadget_id:
        example: "3344556677"
        type: string
      rating:
        example: 5
        type: integer
      review:
        example: Luar biasa! Kinerja cepat dan kamera sangat bagus.
        type: string
      user_id:
        example: "2233445566"
        type: string
    type: object
  controller.Spesifikasi:
    properties:
      _id:
        example: "987654321"
        type: string
      prosesor:
        example: A15 Bionic
        type: string
      ram:
        example: 6
        type: integer
      storage:
        example: 128
        type: integer
    type: object
host: tb-2024-2df3fc45e2ad.herokuapp.com
info:
  contact:
    email: indra@ulbi.ac.id
    name: API Support
    url: https://github.com/jul003
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /deletegadget/{id}:
    delete:
      consumes:
      - application/json
      description: Hapus data gadget.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete data Gadget.
      tags:
      - Gadget
  /gadget:
    get:
      consumes:
      - application/json
      description: Mengambil semua data gadget.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Gadget'
      summary: Get All Data Gadget.
      tags:
      - Gadget
  /gadget/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data gadget.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Gadget'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Gadgets.
      tags:
      - Gadget
  /insertgadget:
    post:
      consumes:
      - application/json
      description: Input data gadget.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqGadget'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Gadget'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data Gadget.
      tags:
      - Gadget
  /insertreview:
    post:
      consumes:
      - application/json
      description: Input data review.
      parameters:
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqReview'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Review'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Insert data Review.
      tags:
      - Review
  /review:
    get:
      consumes:
      - application/json
      description: Mengambil semua data review.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Gadget'
      summary: Get All Data Review.
      tags:
      - Review
  /updategadget/{id}:
    put:
      consumes:
      - application/json
      description: Ubah data gadget.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      - description: Payload Body [RAW]
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.ReqGadget'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Gadget'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update data Gadegt.
      tags:
      - Gadget
schemes:
- https
- http
swagger: "2.0"
